import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { parseEnv } from "node:util";
import { randomBytes } from "node:crypto";
import { exportSPKI, generateKeyPair, SignJWT } from "jose";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const rootDir = join(scriptDir, "../..");
const envPath = join(rootDir, ".env.dev-auth");
const rootEnvPath = join(rootDir, ".env");
const webDistDir = join(rootDir, "apps/evidence-web/dist");

const defaults = {
	NODE_ENV: "development",
	HOST: "127.0.0.1",
	PORT: "3001",
	APP_VERSION: "0.1.3",
	DATABASE_URL: "file:./local.dev-auth.db",
	RUN_DB_MIGRATIONS: "true",
	CLERK_PUBLISHABLE_KEY: "",
	CLERK_SECRET_KEY: "",
	CLERK_AUDIENCE: "jittle-lamp-dev",
	CLERK_AUTHORIZED_PARTIES: "http://127.0.0.1:4173,http://localhost:4173",
	WEB_APP_ORIGIN: "http://127.0.0.1:4173",
	JITTLE_LAMP_API_ORIGIN: "http://127.0.0.1:3001",
	JITTLE_LAMP_WEB_ORIGIN: "http://127.0.0.1:4173",
	JITTLE_LAMP_DEV_AUTH_ENABLED: "true",
	JITTLE_LAMP_DEV_AUTH_USER_ID: "user_jl_dev",
	JITTLE_LAMP_DEV_AUTH_EMAIL: "dev+clerk_test@jittlelamp.local",
	JITTLE_LAMP_DEV_AUTH_NAME: "Jittle Dev",
} as const;

const readEnvFile = (path: string): Record<string, string> => {
	if (!existsSync(path)) return {};
	return Object.fromEntries(
		Object.entries(parseEnv(readFileSync(path, "utf8"))).filter(
			(entry): entry is [string, string] => entry[1] !== undefined,
		),
	);
};

const quoteEnvValue = (value: string): string =>
	`"${value.replace(/\\/g, "\\\\").replace(/\n/g, "\\n").replace(/"/g, '\\"')}"`;

const firstNonEmpty = (...values: Array<string | undefined>): string | undefined =>
	values.find((value) => value !== undefined && value.trim() !== "");

const writeDevAuthEnv = async (): Promise<Record<string, string>> => {
	const rootEnv = readEnvFile(rootEnvPath);
	const existing = readEnvFile(envPath);
	const { privateKey, publicKey } = await generateKeyPair("RS256");
	const publicPem = await exportSPKI(publicKey);
	const userId = firstNonEmpty(
		existing.JITTLE_LAMP_DEV_AUTH_USER_ID,
		rootEnv.JITTLE_LAMP_DEV_AUTH_USER_ID,
		defaults.JITTLE_LAMP_DEV_AUTH_USER_ID,
	) ?? defaults.JITTLE_LAMP_DEV_AUTH_USER_ID;
	const origin = firstNonEmpty(
		existing.JITTLE_LAMP_WEB_ORIGIN,
		rootEnv.JITTLE_LAMP_WEB_ORIGIN,
		defaults.JITTLE_LAMP_WEB_ORIGIN,
	) ?? defaults.JITTLE_LAMP_WEB_ORIGIN;
	const audience = firstNonEmpty(
		existing.CLERK_AUDIENCE,
		rootEnv.CLERK_AUDIENCE,
		defaults.CLERK_AUDIENCE,
	) ?? defaults.CLERK_AUDIENCE;
	const email = firstNonEmpty(
		existing.JITTLE_LAMP_DEV_AUTH_EMAIL,
		rootEnv.JITTLE_LAMP_DEV_AUTH_EMAIL,
		defaults.JITTLE_LAMP_DEV_AUTH_EMAIL,
	) ?? defaults.JITTLE_LAMP_DEV_AUTH_EMAIL;
	const name = firstNonEmpty(
		existing.JITTLE_LAMP_DEV_AUTH_NAME,
		rootEnv.JITTLE_LAMP_DEV_AUTH_NAME,
		defaults.JITTLE_LAMP_DEV_AUTH_NAME,
	) ?? defaults.JITTLE_LAMP_DEV_AUTH_NAME;
	const token = await new SignJWT({
		azp: origin,
		email,
		name,
		scope: "read write org:read org:write evidence:read evidence:write",
		roles: ["admin"],
	})
		.setProtectedHeader({ alg: "RS256" })
		.setIssuer("https://jittle-lamp.local/dev-auth")
		.setSubject(userId)
		.setAudience(audience)
		.setIssuedAt()
		.setExpirationTime("30d")
		.sign(privateKey);

	const env = {
		...defaults,
		...existing,
		CLERK_PUBLISHABLE_KEY: "",
		CLERK_SECRET_KEY: "",
		CLERK_AUDIENCE: audience,
		CLERK_JWT_KEY: publicPem,
		APP_SECRET: firstNonEmpty(
			existing.APP_SECRET,
			rootEnv.APP_SECRET,
			`dev-auth-${randomBytes(24).toString("hex")}`,
		) ?? `dev-auth-${randomBytes(24).toString("hex")}`,
		JITTLE_LAMP_DEV_AUTH_USER_ID: userId,
		JITTLE_LAMP_DEV_AUTH_EMAIL: email,
		JITTLE_LAMP_DEV_AUTH_NAME: name,
		JITTLE_LAMP_DEV_AUTH_TOKEN: token,
	};

	const orderedKeys = [
		"NODE_ENV",
		"HOST",
		"PORT",
		"APP_VERSION",
		"APP_SECRET",
		"DATABASE_URL",
		"RUN_DB_MIGRATIONS",
		"CLERK_PUBLISHABLE_KEY",
		"CLERK_SECRET_KEY",
		"CLERK_JWT_KEY",
		"CLERK_AUDIENCE",
		"CLERK_AUTHORIZED_PARTIES",
		"WEB_APP_ORIGIN",
		"JITTLE_LAMP_API_ORIGIN",
		"JITTLE_LAMP_WEB_ORIGIN",
		"JITTLE_LAMP_DEV_AUTH_ENABLED",
		"JITTLE_LAMP_DEV_AUTH_USER_ID",
		"JITTLE_LAMP_DEV_AUTH_EMAIL",
		"JITTLE_LAMP_DEV_AUTH_NAME",
		"JITTLE_LAMP_DEV_AUTH_TOKEN",
	] as const;

	const body = [
		"# Generated by bun run dev:test-auth:setup",
		"# Local only. Do not commit.",
		...orderedKeys.map((key) => `${key}=${quoteEnvValue(env[key] ?? "")}`),
		"",
	].join("\n");
	writeFileSync(envPath, body);
	return env;
};

const contentTypeFor = (path: string): string => {
	if (path.endsWith(".html")) return "text/html; charset=utf-8";
	if (path.endsWith(".js")) return "text/javascript; charset=utf-8";
	if (path.endsWith(".css")) return "text/css; charset=utf-8";
	if (path.endsWith(".svg")) return "image/svg+xml";
	if (path.endsWith(".json")) return "application/json; charset=utf-8";
	if (path.endsWith(".png")) return "image/png";
	return "application/octet-stream";
};

const serveWebDist = (): ReturnType<typeof Bun.serve> =>
	Bun.serve({
		hostname: "127.0.0.1",
		port: 4173,
		fetch(request) {
			const url = new URL(request.url);
			const cleanPath = decodeURIComponent(url.pathname).replace(/^\/+/, "");
			const requestedPath = join(webDistDir, cleanPath || "index.html");
			const path = existsSync(requestedPath) ? requestedPath : join(webDistDir, "index.html");
			return new Response(Bun.file(path), {
				headers: { "content-type": contentTypeFor(path) },
			});
		},
	});

const run = async (): Promise<void> => {
	const env = await writeDevAuthEnv();
	const mergedEnv = { ...process.env, ...env };
	console.log(`Wrote ${envPath}`);
	console.log("Building evidence-web with local test auth...");
	const build = Bun.spawn(["bun", "--no-env-file", "run", "--cwd", "apps/evidence-web", "build"], {
		cwd: rootDir,
		env: mergedEnv,
		stdout: "inherit",
		stderr: "inherit",
	});
	const buildExit = await build.exited;
	if (buildExit !== 0) process.exit(buildExit);

	const backendEnv = {
		...mergedEnv,
		CLERK_PUBLISHABLE_KEY: "",
		CLERK_SECRET_KEY: "",
	};
	const backend = Bun.spawn(["bun", "--no-env-file", "run", "--cwd", "apps/backend", "dev"], {
		cwd: rootDir,
		env: backendEnv,
		stdout: "inherit",
		stderr: "inherit",
	});
	const server = serveWebDist();
	console.log("");
	console.log("Jittle Lamp test auth is running");
	console.log(`Web: http://127.0.0.1:${server.port}`);
	console.log(`API: http://${env.HOST}:${env.PORT}`);
	console.log(`Account: ${env.JITTLE_LAMP_DEV_AUTH_EMAIL} (${env.JITTLE_LAMP_DEV_AUTH_USER_ID})`);
	console.log("");

	const shutdown = (): void => {
		server.stop(true);
		backend.kill();
	};
	process.on("SIGINT", shutdown);
	process.on("SIGTERM", shutdown);
	const exitCode = await backend.exited;
	server.stop(true);
	process.exit(exitCode);
};

const mode = process.argv[2] ?? "run";

if (mode === "setup") {
	const env = await writeDevAuthEnv();
	console.log(`Wrote ${envPath}`);
	console.log(`Account: ${env.JITTLE_LAMP_DEV_AUTH_EMAIL} (${env.JITTLE_LAMP_DEV_AUTH_USER_ID})`);
	console.log("Start everything with: bun run dev:test-auth");
} else if (mode === "run") {
	await run();
} else {
	console.error("Usage: bun run dev:test-auth[:setup]");
	process.exit(1);
}
